name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Self test
        id: selftest
        uses: Secful/python-container-action/output-action@master

      - name: Self test
        id: printest
        uses: Secful/python-container-action/print-action@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"

